/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserInfo } from '../../models/user-info';

export interface UpdateUrls$Params {
  resumeUrl?: string;
  githubUrl?: string;
  Authorization: string;
}

export function updateUrls(http: HttpClient, rootUrl: string, params: UpdateUrls$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfo>> {
  const rb = new RequestBuilder(rootUrl, updateUrls.PATH, 'patch');
  if (params) {
    rb.query('resumeUrl', params.resumeUrl, {});
    rb.query('githubUrl', params.githubUrl, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserInfo>;
    })
  );
}

updateUrls.PATH = '/api/user/{userId}/update-urls';
