/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserInfo } from '../models/user-info';
export interface InterestInCompany {
  company?: string;
  id?: number;
  student?: UserInfo;
}
