/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserInfo } from '../models/user-info';
export interface Review {
  company?: string;
  id?: number;
  rating?: number;
  reviewDate?: string;
  reviewText?: string;
  reviewer?: UserInfo;
}
