/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInfo {
  email?: string;
  enabled?: boolean;
  id?: number;
  name?: string;
  password?: string;
  roles?: string;
}
