/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Review } from '../../models/review';

export interface AddReview$Params {
  username: string;
  company: string;
  rating: number;
  reviewText?: string;
}

export function addReview(http: HttpClient, rootUrl: string, params: AddReview$Params, context?: HttpContext): Observable<StrictHttpResponse<Review>> {
  const rb = new RequestBuilder(rootUrl, addReview.PATH, 'post');
  if (params) {
    rb.query('username', params.username, {});
    rb.query('company', params.company, {});
    rb.query('rating', params.rating, {});
    rb.query('reviewText', params.reviewText, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Review>;
    })
  );
}

addReview.PATH = '/api/reviews/add';
