/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Internship } from '../../models/internship';

export interface GetInternshipById$Params {
  id: number;
  Authorization: string;
}

export function getInternshipById(http: HttpClient, rootUrl: string, params: GetInternshipById$Params, context?: HttpContext): Observable<StrictHttpResponse<Internship>> {
  const rb = new RequestBuilder(rootUrl, getInternshipById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Internship>;
    })
  );
}

getInternshipById.PATH = '/api/internship/viewInternship/{id}';
