/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserControllerService } from './services/user-controller.service';
export { ReviewControllerService } from './services/review-controller.service';
export { InternshipControllerService } from './services/internship-controller.service';
export { InterestInCompanyControllerService } from './services/interest-in-company-controller.service';
export { ApplicationControllerService } from './services/application-controller.service';
export { TestService } from './services/test.service';
