/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InterestInCompany } from '../../models/interest-in-company';

export interface ExpressInterest$Params {
  username: string;
  company: string;
}

export function expressInterest(http: HttpClient, rootUrl: string, params: ExpressInterest$Params, context?: HttpContext): Observable<StrictHttpResponse<InterestInCompany>> {
  const rb = new RequestBuilder(rootUrl, expressInterest.PATH, 'post');
  if (params) {
    rb.query('username', params.username, {});
    rb.query('company', params.company, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InterestInCompany>;
    })
  );
}

expressInterest.PATH = '/api/interests/express';
