/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InterestInCompany } from '../../models/interest-in-company';

export interface GetInterestsByCompany$Params {
  company: string;
}

export function getInterestsByCompany(http: HttpClient, rootUrl: string, params: GetInterestsByCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InterestInCompany>>> {
  const rb = new RequestBuilder(rootUrl, getInterestsByCompany.PATH, 'get');
  if (params) {
    rb.path('company', params.company, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InterestInCompany>>;
    })
  );
}

getInterestsByCompany.PATH = '/api/interests/company/{company}';
