/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InterestInCompany } from '../../models/interest-in-company';

export interface GetInterestsByStudent$Params {
  studentId: number;
}

export function getInterestsByStudent(http: HttpClient, rootUrl: string, params: GetInterestsByStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InterestInCompany>>> {
  const rb = new RequestBuilder(rootUrl, getInterestsByStudent.PATH, 'get');
  if (params) {
    rb.path('studentId', params.studentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InterestInCompany>>;
    })
  );
}

getInterestsByStudent.PATH = '/api/interests/student/{studentId}';
