/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Application } from '../../models/application';

export interface GetApplicationsByInternship$Params {
  internshipId: number;
}

export function getApplicationsByInternship(http: HttpClient, rootUrl: string, params: GetApplicationsByInternship$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Application>>> {
  const rb = new RequestBuilder(rootUrl, getApplicationsByInternship.PATH, 'get');
  if (params) {
    rb.path('internshipId', params.internshipId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Application>>;
    })
  );
}

getApplicationsByInternship.PATH = '/api/applications/internship/{internshipId}';
